
spring.application.name=EventX
server.port=9192

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.mvc.log-request-details=true



spring.datasource.url=jdbc:mariadb://localhost:3306/eventx
spring.datasource.username=root
spring.datasource.password=1234

#jpa vendor adapter configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=abcde


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=1eventxtest@gmail.com
spring.mail.password=xxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

